LDFLAGS=-std=c++17 -lstdc++
CXXFLAGS=-std=c++17 -g

day01: day01.o
day02: day02.o
day03: day03.o
day04: day04.o
day05: day05.o
day06: day06.o
day07: day07.o
clean: 
	rm -f day01 day02 day03 day04 day05 day06 day07